### ISSUE TITLE
请问此主题主页宽度如何修改？

### ISSUE THREAD

**Issue by Sherlock2435** [Sanarous/hexo-theme-next5-polished#1]
本人前端小白无从下手,在我的电脑上显示两端留白过多。

**Comment by Sanarous** [comment]
在主题目录下，找到source/css/custom/custom.styl文件，在文件中搜索main—inner，找到width:900px这个设置，把900改大一点就可以发自我的华为手机-------- 原始邮件 --------主题：[Sanarous/hexo-theme-next5-polished] 请问此主题主页宽度如何修改？ (#1)发件人：Sherlock 收件人：Sanarous/hexo-theme-next5-polished 抄送：Subscribed 本人前端小白无从下手,在我的电脑上显示两端留白过多。

**Comment by Sherlock2435** [comment]
文件中无main-inner关键词，我手动添加了 `.main-inner { width: 1200px; }`  ,`hexo c->hexo g->hexo s`在我的谷歌浏览器上没有发生变化,天气条也因为宽度不能完全显示。
![image](https://user-images.githubusercontent.com/35016940/60317356-418c2a00-99a1-11e9-90b8-9b941058bb30.png)

**Comment by Sanarous** [comment]
在文件中加入以下代码：
```css
@media (min-width: 1000px)
.container .main-inner {
    width: 900px !important;
}
```
900这里改大一点
